### PR TITLE
Menubar icon was removed in a previous commit and not replaced

### PR DESCRIPTION
**Pull request by sillywilly42**

### CODE REVIEW

**Comment by verycarefully** [comment]
Thanks for identifying this fix, but unfortunately we can't use the G icon in the open source release. It should be replaced with a dot, circle or some other placeholder icon.

**Comment by sillywilly42** [comment]
@verycarefully @russellhancox  How do you feel about a dog which, at one and the same time, is also a cow?

**Comment by verycarefully** [comment]
I would feel great about a dog which is also a cow, but [Dogcow logo [is] perhaps trademark by Apple Computer Inc.](http://clarus.chez-alice.fr/faq.php) Maybe something more simplistic?

**Comment by verycarefully** [comment]
I made https://github.com/google/macops-MOMenu/pull/5 with generic icons.

**Pull request closed without merging**
